In [1]:
import numpy as np
import xarray as xr

In [2]:
his102=xr.open_dataset("run_salt_20160520-v102/DFM_OUTPUT_flowfm/flowfm_0000_his.nc")
his103=xr.open_dataset("run_salt_20160520-v103/DFM_OUTPUT_flowfm/flowfm_0000_his.nc")

In [3]:
z_w=his103.isel(stations=7).zcoordinate_w.values

In [11]:
np.diff(z_w)

array([[       nan,        nan,        nan,        nan, 0.13706239,
        0.1321673 , 0.1321673 , 0.13706239, 0.1321673 , 0.13706239,
        0.1321673 , 0.1321673 , 0.13706239, 0.1321673 , 0.1321673 ,
        0.13706239, 0.1321673 , 0.1321673 , 0.13706239, 0.1321673 ,
        0.1321673 , 0.13706239, 0.1321673 , 0.02062669,        nan,
               nan,        nan,        nan]])

In [4]:
dz=np.diff(z_w)
dz=np.median(dz[np.isfinite(dz)])
dz # 0.1768 m
z_w

array([[       nan,        nan,        nan,        nan, 0.03392893,
        0.17099132, 0.30315862, 0.43532593, 0.57238832, 0.70455562,
        0.84161801, 0.97378532, 1.10595262, 1.24301501, 1.37518231,
        1.50734962, 1.64441201, 1.77657931, 1.90874662, 2.04580901,
        2.17797631, 2.31014361, 2.447206  , 2.57937331, 2.6       ,
               nan,        nan,        nan,        nan]])

In [10]:
-0.5 + np.arange(28)*dz # That works out.


array([-0.5       , -0.3678327 , -0.23566539, -0.10349809,  0.02866922,
        0.16083652,  0.29300383,  0.42517113,  0.55733843,  0.68950574,
        0.82167304,  0.95384035,  1.08600765,  1.21817495,  1.35034226,
        1.48250956,  1.61467687,  1.74684417,  1.87901148,  2.01117878,
        2.14334608,  2.27551339,  2.40768069,  2.539848  ,  2.6720153 ,
        2.80418261,  2.93634991,  3.06851721])

In [5]:
dz

0.13216730420079004

In [9]:
(3.25 + 0.25)/28

0.125